name: 'Main'

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]
permissions:  # added using https://github.com/step-security/secure-repo
  contents: read

jobs:
  CodeQL-Build:
    # CodeQL runs on ubuntu-latest
    runs-on: ubuntu-latest

    permissions:
      # required for all workflows
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0

      # Initializes the CodeQL tools for scanning.
      - name: Initialize CodeQL
        uses: github/codeql-action/init@c0d1daa7f7e14667747d73a7dbbe8c074bc8bfe2 # v2.22.9

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@c0d1daa7f7e14667747d73a7dbbe8c074bc8bfe2 # v2.22.9
